### ISSUE TITLE
Add the StaticShowdown website

### ISSUE THREAD

**Issue by waldyrious** [aharris88/awesome-static-website-services#26]
I'd submit a PR, but I'm not sure which section to add it to.

https://staticshowdown.com

**Comment by aharris88** [comment]
Yeah, it's not really a service. It's a contest, but I think it should be added to this list somewhere. I think at the end, you could just add a category called Contests.

**Comment by waldyrious** [comment]
OK, I'll send a PR :) By the way, are there entries from https://github.com/anaibol/awesome-serverless you think could be added as well?

**Comment by aharris88** [comment]
Cool! I haven't seen that list before, I'm sure there's some stuff from there that I'm missing.

**Comment by waldyrious** [comment]
Let me know when you take a look, then :) -- it would be nicer to add it all in one PR, I think.

**Comment by aharris88** [comment]
Ok, I opened an issue #27 for it.

**Comment by waldyrious** [comment]
Ok. In that case, I'll send a PR for this one.
