### ISSUE TITLE
Suggestion: provide a badge

### ISSUE THREAD

**Issue by waldyrious** [aharris88/awesome-static-website-services#30]
This project could feature a shields.io badge for static website projects to use :) For example websites hosted statically (without generators like jekyll) on github or [other hosts](https://github.com/aharris88/awesome-static-website-services#static-hosting). Something like this:

[![Static Website](https://img.shields.io/badge/hosting-static-green.svg)](https://github.com/aharris88/awesome-static-website-services#awesome-static-website-services-)

```
[![Static Website](https://img.shields.io/badge/hosting-static-green.svg)](https://github.com/aharris88/awesome-static-website-services)
```

(We could make the badge link to [another page](https://en.wikipedia.org/wiki/Static_web_page), of course -- this is just a suggestion.)

**Comment by aharris88** [comment]
That's an interesting idea. I haven't really heard of people using those badges on websites before (just on github readmes).

**Comment by waldyrious** [comment]
I meant in the README of the websites' repos, yes :) examples: https://github.com/waldyrious/primerpedia#primerpedia, https://github.com/waldyrious/wikispeed.

It would be nice to promote a recognizable badge so people could help spread the word about the possibilities of (and quickly identify) static websites.

**Comment by aharris88** [comment]
Ok, that makes sense. If you put in a pull request, I'd love to add this.

**Comment by waldyrious** [comment]
Sure. Do you have any thoughts on the example badge/code I gave above?

**Comment by aharris88** [comment]
I have no ideas... Actually, I'm beginning to think I may not want to do this, unless I start to see that other lists are doing it. I don't think it would be clear what it's linking to until you clicked.

**Comment by waldyrious** [comment]
The link isn't required; in fact, many badges (especially shield.io ones) only provide an image, with no link. We could e.g. link it to the Wikipedia page instead, or remove the link altogether. The goal isn't to promote *this* list, but provide a visually identifiable mark that people could add to their static website projects and advertise the static-ness :)
