### ISSUE TITLE
Add DatoCMS to Online Editors

### ISSUE THREAD

**Issue by aharris88** [aharris88/awesome-static-website-services#38]
https://www.datocms.com/

**Comment by iamchriswick** [comment]
Hi! Awesome start! Could I also suggest a list of CMSs for Static Websites? Like https://gohugo.io/ and all the others =)

**Comment by aharris88** [comment]
Thanks for the suggestion. I actually recently removed static site generators from this list to make it more focuses on services instead of CMSs, generators, editors, or hosts. I plan on added related lists (see #40). And Hugo is already on https://github.com/myles/awesome-static-generators.
